name: Run Daily Script
on:
  workflow_dispatch:
  schedule:
    #- cron: '0 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'  # Replace with the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install scikit-learn
          pip install numpy
          pip install tensorflow

      - name: Update yesterday CSV
        run: python day-proc.py
        
      - name: Evaluate model
        run: python eval-model.py

      - name: Live totals
        run: python live-totals.py
      
      - name: Send SMS
        run: python sms-update.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          git add data/LR-yesterday.csv
          git add data/results.csv
          git add data/scores.csv
          git add lstm-model.h5
          git commit -m "Update CSV files and model"
          git push
